app_newspaper/app_newspaper/urls.py
'''
SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (app_newspaper/urls.py)
FECHA: 29/09/2024
VERSION: 1.0
'''

# Importacion de la clase admin para registrar los modelos en el panel de administracion
from django.contrib import admin

# Importacion de la funcion path para definir las rutas de la aplicacion y 
# la funcion include para incluir las rutas de la aplicacion accounts
from django.urls import path, include

# Importacion de la clase TemplateView para renderizar la pagina principal
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('articles/', include('articles.urls')),
    path('',include('pages.urls')),
    path('', TemplateView.as_view(template_name='home.html'),name='home'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_newspaper/pages/urls.py
'''
SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (pages/urls.py)
FECHA: 29/09/2024
VERSION: 1.0
'''

# Importacion de la funcion path para definir las rutas de la aplicacion
from django.urls import path

# Importacion de la clase HomePageView para renderizar la pagina principal
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'), # Definicion de la ruta de la pagina principal
]

app_newspaper/accounts/models.py
'''
SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (accounts/models.py)
FECHA: 29/09/2024
VERSION: 1.0
'''

# Importamos el modelo AbstractUser de Django.
from django.contrib.auth.models import AbstractUser

# Importamos el modelo models de Django.
from django.db import models

# Importamos el modelo User de Django.
from django.conf import settings

# Create your models here.

class CustomUser(AbstractUser):
    '''
    Clase CustomUser que hereda de AbstractUser. Esta clase se encarga de
    definir los campos de la tabla de la base de datos que se va a crear
    para el modelo CustomUser.
    '''
    
    # Definimos el camopo age como un campo entero positivo.
    age = models.PositiveIntegerField(null=True, blank=True)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics/', default='default.jpg')
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers", blank=True)

    def __str__(self):
        return f'Perfil de {self.user.username}'

    def total_followers(self):
        return self.followers.count()

app_newspaper/articles/models.py
'''
SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (articles/models.py)
FECHA: 29/09/2024
VERSION: 1.0
'''
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    image = models.ImageField(upload_to='article_images/', blank=True, null=True)
    
    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE,)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    
    def __str__(self):
        return self.comment
    
    def get_absolute_url(self):
        return reverse('article_list')
    

app_newspaper/templates/article_delete.html
{% extends "base.html" %}

{% comment %} 

SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (templates/article_delete.html)
FECHA: 29/09/2024
VERSION: 1.0

{% endcomment %}

<!--  templates/article_delete.html -->


{% block content %}
<div class="delete-article-container">
  <h1>Delete</h1>
  <form method="post" class="delete-article-form">
    {% csrf_token %}
    <p>Are you sure you want to delete <b>"{{ article.title }}"</b>?</p>
    <button type="submit" class="delete-button">
      <ion-icon name="trash-outline"></ion-icon>
      Confirm
    </button>
  </form>
</div>
{% endblock content %}


    

app_newspaper/templates/article_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% comment %} 

SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (templates/article_detail.html)
FECHA: 29/09/2024
VERSION: 1.0

{% endcomment %}

<!--  templates/article_detail.html -->

{% block content %}


<div class="article-entry">
    <h2 class="article-title">{{ object.title }}</h2>
    <p class="article-meta">by {{ object.author }} | {{ object.date }}</p>
    <p class="article-content">{{ article.body }}</p>
</div>

<hr class="divider">

<h4 class="comment-section-title">Comentarios</h4>
<div class="comment-list">
    {% for comment in article.comment_set.all %}
        <div class="comment fade-in">
            <p class="comment-author">{{ comment.author }}</p>
            <p class="comment-text">{{ comment }}</p>
            {% if comment.author == request.user %}
                <a href="{% url 'comment_edit' comment.pk %}" class="edit-link">Edit</a>
            {% endif %}
        </div>
    {% empty %}
        <p class="no-comments">No comments yet. Be the first to comment!</p>
    {% endfor %}
</div>

<hr class="divider">

<!-- Formulario de comentarios -->

<form action="" method="post" class="comment-form">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
</form>

<p class="back-link">Back to <a href="{% url 'article_list' %}">All Articles</a>.</p>



    {% comment %} <div class="article-entry">
        <h2 style="color: var(--color-texto);">{{ object.title }}</h2>
        <p style="color: var(--color-texto);">by {{ object.author }} | {{ object.date }}</p>
        <p style="color: var(--color-texto);">{{ object.content }}</p>
    </div>
    <hr style="color: var(--color-texto); border: solid 2px">
    <h4 style="color: var(--color-texto);">Comments</h4>
    {% for comment in article.comment_set.all %}
        <p style="color: var(--color-texto);">{{ comment.author }} &middot; {{ comment }}</p>
        {% if comment.author == request.user %}
            <a href="{% url 'comment_edit' comment.pk %}">Edit</a>
        {% endif %}
    {% endfor %}
    <hr>
    <!-- Formulario de comentarios para postear -->
    <h4 style="color: var(--color-texto);">Add a Comment</h4>
    <form action="" method="post" style="color: var(--color-texto);">
        {%csrf_token%}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>      
    <p style="color: var(--color-texto);">Back to <a href="{% url 'article_list' %}">All Articles</a>.</p>    {% endcomment %}  
{% endblock content %}
    

app_newspaper/templates/article_edit.html
{% extends "base.html" %}


{% comment %} 

SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (templates/article_edit.html )
FECHA: 29/09/2024
VERSION: 1.0

{% endcomment %}

<!--  templates/article_edit.html  -->


{% load crispy_forms_tags %}
{% block content %}
  <div class="edit-page">
    <h1>Edit</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-update" type="submit">Update</button>
    </form>
  </div>
{% endblock content %}

{% comment %} {%load crispy_forms_tags %}


{% block content %}
    <h1 style="color: var(--color-texto);">Edit</h1>
    <form action="" method="post"style="color: var(--color-texto);">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info ml-2" type="submit">Update</button>
    </form>       
{% endblock content %} {% endcomment %}
    

app_newspaper/templates/article_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% comment %} 

SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (templates\article_list.html)
FECHA: 29/10/2024
VERSION: 1.0

{% endcomment %}

<!--  templates\article_list.html -->
{% block title %}Post{% endblock title %}

{% block content %}
<div class="custom-container mt-4">
    <h1>A r t i c l e s</h1>
    {% for article in article_list %}
        <div class="post-container" style="position: relative;">
            <!-- Enlace superpuesto: este <a> cubre todo el contenedor -->
            <a href="{% url 'article_detail' article.pk %}" class="custom-overlay-link"></a>
            
            <!-- Contenido visible e interactivo con z-index mayor -->
            <div class="post-content">
                <!-- Header: Foto de perfil y usuario -->
                <div class="perfil-container custom-d-flex custom-align-items-center"> 
                    <a href="{% url 'profile' username=article.author.username %}" >     
                        <img src="{{ article.author.profile.profile_picture.url }}" alt="Foto de perfil" class="profile-pic">
                    </a>
                    <a href="{% url 'profile' username=article.author.username %}" style="text-decoration: none; color: inherit;">
                        <strong class="custom-ms-2">{{ article.author.username }}</strong>
                    </a>
                    {% if request.user == article.author %}
                        <div class="menu-container">
                            <!-- Botón de opciones -->
                            <button class="menu-toggle">
                                <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                            </button>
                    
                            <!-- Menú desplegable -->
                            <div class="menu-dropdown">
                                <a href="{% url 'article_edit' article.pk %}"><ion-icon name="create-outline"></ion-icon> Editar</a>
                                <a href="{% url 'article_delete' article.pk %}"><ion-icon name="trash-outline"></ion-icon> Eliminar</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="menu-container">
                            <!-- Botón de opciones -->
                            <button class="menu-toggle">
                                <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                            </button>
                    
                            <!-- Menú desplegable -->
                            <div class="menu-dropdown">
                                <a href="{% url 'profile' username=article.author.username %}"><ion-icon name="body-outline"></ion-icon></ion-icon> Autor</a>
                                <a href="{% url 'article_detail' article.pk %}"><ion-icon name="bookmark-outline"></ion-icon> Detalle</a>
                            </div>
                        </div>
                    {% endif %}
                    
                </div>

                <!-- Imagen del post -->
                {% if article.image %}
                    <div class="post-image">
                        <img src="{{ article.image.url }}" alt="{{ article.title }}">
                    </div>
                {% endif %}

                <!-- Texto del post -->
                <div class="card-body  publicacion" >
                    <a href="{% url 'article_detail' article.pk %}" class="custom-overlay-link-publicacion"></a>
                        
                            <h5 class="mb-0" style="text-transform: uppercase;">{{ article.title }}</h5>
                            <p>{{ article.body }}</p>
                        
                </div>

                <!-- Botones de interacciones -->
                <div class="comentarios-container">
                    <button class="custom-comment-toggle">
                        <ion-icon name="chatbubbles-outline"></ion-icon> Comentarios
                    </button>
                </div>

                <!-- Sección de comentarios -->
                <div class="comments-section">
                    <div class="comment-list">
                        {% for comment in article.comment_set.all %}
                            <div class="mb-4">
                                <img src="{{ comment.author.profile.profile_picture.url }}" alt="Foto de perfil" class="foto-comentario">
                                <a href="{% url 'profile' username=comment.author.username %}" style="text-decoration: none; color: inherit;">
                                <strong>{{ comment.author }}</strong> &middot;
                                </a>
                                <small class="text-muted">{{ comment.date_posted|default:"Just now" }}</small>
                                {% if request.user == comment.author %}
                                    <div class="menu-container float-end">
                                        <!-- Botón de opciones -->
                                        <button class="menu-toggle">
                                            <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                                        </button>
                                
                                        <!-- Menú desplegable -->
                                        <div class="menu-dropdown">
                                            <a href="{% url 'comment_edit' comment.pk %}"><ion-icon name="create-outline"></ion-icon> Editar</a>
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="menu-container float-end">
                                        <!-- Botón de opciones -->
                                        <button class="menu-toggle">
                                            <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                                        </button>
                                
                                        <!-- Menú desplegable -->
                                        <div class="menu-dropdown">
                                            <a class="btn danger"><ion-icon name="alert-circle-outline"></ion-icon></ion-icon>Reportar</a>
                                        </div>
                                    </div>
                                {% endif %}
                                <p class="mb-0">{{ comment }}</p>
                            </div>
                        {% empty %}
                            <p class="text-muted">No comments yet. Be the first to comment!</p>
                        {% endfor %}
                    </div>
                    <a class="boton-comentario" href="{% url 'article_detail' article.pk %}">
                        <ion-icon name="pencil-outline"></ion-icon>
                        <span>comentar</span>
                    </a>

                    
                </div>
            </div><!-- /.post-content -->
        </div><!-- /.post-container -->
    {% endfor %}
</div><!-- /.custom-container -->
{% endblock content %}

{% comment %} 
{% block content %}

    
        {% for article in article_list %}
            <div class="post-container"  >
                <!-- Header: Foto de perfil y usuario -->
                <div class="perfil-container d-flex align-items-center">      
                    <img src="{{ article.author.profile.profile_picture.url }}" alt="Foto de perfil" class="profile-pic" >
                    <strong class="ms-2">{{ article.author.username }}</strong>
                    <div>
                        {% if request.user == article.author %}
                            <a href="{% url 'article_edit' article.pk %}" class="btn btn-sm btn-outline-primary">Edit</a>
                            <a href="{% url 'article_delete' article.pk %}" class="btn btn-sm btn-outline-danger">Delete</a>
                        {% endif %}
                    </div>
                    
                </div>

                <!-- Imagen del post -->
                {% if article.image %}
                    <div class="post-image">
                            <img src="{{ article.image.url }}" alt="{{ article.title }}">
                    </div>
                {% endif %}
                

                <!-- Texto del post -->
                <div class="card-body ">
                    <h5 class="mb-0">{{ article.title }}</h5>
                    <div class="publicacion">
                        <p>{{ article.body }}</p>
                    </div>
                </div>

                <!-- Botones de interacciones -->
                <div class="comentarios-container" >
                    <button class=" comment-toggle"><ion-icon name="chatbubbles-outline"></ion-icon> Comentarios</button>
                </div>

                <!-- Sección de comentarios -->
                <div class="comments-section" style="display: none;">
                    <div class="comment-list">
                        {% for comment in article.comment_set.all %}
                            <div class="mb-2">
                                <img src="{{ comment.author.profile.profile_picture.url }}" alt="Foto de perfil" class="foto-comentario" >
                                <strong>{{ comment.author }}</strong> &middot; 
                                <small class="text-muted">{{ comment.date_posted|default:"Just now" }}</small>
                                <p class="mb-0">{{ comment }}</p>
                            </div>
                        {% empty %}
                            <p class="text-muted">No comments yet. Be the first to comment!</p>
                        {% endfor %}
                    </div>
                    <form method="post" action="{% url 'article_detail' article.pk %}">
                        {% csrf_token %}
                        <input type="text" class="new-comment form-control mt-2" name="comment" placeholder="Escribe un comentario..." required>
                        <button type="submit" class="btn btn-primary add-comment">Post</button>
                    </form>
                </div>
            </div>
        {%endfor%}
    

{% endblock content %} {% endcomment %}


{% comment %}

{% block title %}Article List{% endblock title %}

{% block content %}
<div class="container mt-4" >
    {% for article in article_list %}
        <!-- Card for each article -->
        <div class="card mb-4 shadow-sm">
            <div class="card-header bg-light d-flex justify-content-between align-items-center">
                <div>
                    <h5 class="mb-0">{{ article.title }}</h5>
                    <small class="text-muted">by {{ article.author }} &middot; {{ article.date }}</small>
                </div>
                <div>
                    {% if request.user == article.author %}
                        <a href="{% url 'article_edit' article.pk %}" class="btn btn-sm btn-outline-primary">Edit</a>
                        <a href="{% url 'article_delete' article.pk %}" class="btn btn-sm btn-outline-danger">Delete</a>
                    {% endif %}
                </div>
            </div>
            <div class="card-body">
                {% if article.image %}
                    <img src="{{ article.image.url }}" alt="{{ article.title }}" class="img-fluid mb-3">
                {% endif %}
                <p>{{ article.body }}</p>
            </div>
            <div class="card-footer bg-light">
                <ion-icon name="chatbubbles-outline"></ion-icon>
                <h6 class="mb-3">Comments:</h6>
                {% for comment in article.comment_set.all %}
                    <div class="mb-2">
                        <strong>{{ comment.author }}</strong> &middot; 
                        <small class="text-muted">{{ comment.date_posted|default:"Just now" }}</small>
                        <p class="mb-0">{{ comment }}</p>
                    </div>
                {% empty %}
                    <p class="text-muted">No comments yet. Be the first to comment!</p>
                {% endfor %}
                <form method="post" action="{% url 'article_detail' article.pk %}">
                    {% csrf_token %}
                    <div class="input-group mt-3">
                        <input type="text" class="form-control" name="comment" placeholder="Write a comment..." required>
                        <button type="submit" class="btn btn-primary">Post</button>
                    </div>
                </form>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}
{% endcomment %}

    

app_newspaper/templates/article_search.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="color: var(--color-texto);">Resultados de búsqueda</h2>
    
    <div class="container mt-4">
        {% if query %}
            <p style="color: var(--color-texto);">Buscaste: <strong>{{ query }}</strong></p>
        {% endif %}
    
        {% if results %}
            {% for article in results %}
                <!-- Card para cada artículo encontrado -->
                <div class="post-container" style="position: relative;">
                    <!-- Enlace superpuesto: este <a> cubre todo el contenedor -->
                    <a href="{% url 'article_detail' article.pk %}" class="custom-overlay-link"></a>
                    
                    <!-- Contenido visible e interactivo con z-index mayor -->
                    <div class="post-content">
                        <!-- Header: Foto de perfil y usuario -->
                        <div class="perfil-container custom-d-flex custom-align-items-center"> 
                            <a href="{% url 'profile' username=article.author.username %}" >     
                                <img src="{{ article.author.profile.profile_picture.url }}" alt="Foto de perfil" class="profile-pic">
                            </a>
                            <a href="{% url 'profile' username=article.author.username %}" style="text-decoration: none; color: inherit;">
                                <strong class="custom-ms-2">{{ article.author.username }}</strong>
                            </a>
                            {% if request.user == article.author %}
                                <div class="menu-container">
                                    <!-- Botón de opciones -->
                                    <button class="menu-toggle">
                                        <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                                    </button>
                            
                                    <!-- Menú desplegable -->
                                    <div class="menu-dropdown">
                                        <a href="{% url 'article_edit' article.pk %}"><ion-icon name="create-outline"></ion-icon> Editar</a>
                                        <a href="{% url 'article_delete' article.pk %}"><ion-icon name="trash-outline"></ion-icon> Eliminar</a>
                                    </div>
                                </div>
                            {% else %}
                                <div class="menu-container">
                                    <!-- Botón de opciones -->
                                    <button class="menu-toggle">
                                        <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                                    </button>
                            
                                    <!-- Menú desplegable -->
                                    <div class="menu-dropdown">
                                        <a href="{% url 'profile' username=article.author.username %}"><ion-icon name="body-outline"></ion-icon></ion-icon> Autor</a>
                                        <a href="{% url 'article_detail' article.pk %}"><ion-icon name="bookmark-outline"></ion-icon> Detalle</a>
                                    </div>
                                </div>
                            {% endif %}
                            
                        </div>
        
                        <!-- Imagen del post -->
                        {% if article.image %}
                            <div class="post-image">
                                <img src="{{ article.image.url }}" alt="{{ article.title }}">
                            </div>
                        {% endif %}
        
                        <!-- Texto del post -->
                        <div class="card-body  publicacion" >
                            <a href="{% url 'article_detail' article.pk %}" class="custom-overlay-link-publicacion"></a>
                                
                                    <h5 class="mb-0" style="text-transform: uppercase;">{{ article.title }}</h5>
                                    <p>{{ article.body }}</p>
                                
                        </div>
        
                        <!-- Botones de interacciones -->
                        <div class="comentarios-container">
                            <button class="custom-comment-toggle">
                                <ion-icon name="chatbubbles-outline"></ion-icon> Comentarios
                            </button>
                        </div>
        
                        <!-- Sección de comentarios -->
                        <div class="comments-section">
                            <div class="comment-list">
                                {% for comment in article.comment_set.all %}
                                    <div class="mb-4">
                                        <img src="{{ comment.author.profile.profile_picture.url }}" alt="Foto de perfil" class="foto-comentario">
                                        <a href="{% url 'profile' username=comment.author.username %}" style="text-decoration: none; color: inherit;">
                                        <strong>{{ comment.author }}</strong> &middot;
                                        </a>
                                        <small class="text-muted">{{ comment.date_posted|default:"Just now" }}</small>
                                        {% if request.user == comment.author %}
                                            <div class="menu-container float-end">
                                                <!-- Botón de opciones -->
                                                <button class="menu-toggle">
                                                    <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                                                </button>
                                        
                                                <!-- Menú desplegable -->
                                                <div class="menu-dropdown">
                                                    <a href="{% url 'comment_edit' comment.pk %}"><ion-icon name="create-outline"></ion-icon> Editar</a>
                                                </div>
                                            </div>
                                        {% else %}
                                            <div class="menu-container float-end">
                                                <!-- Botón de opciones -->
                                                <button class="menu-toggle">
                                                    <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                                                </button>
                                        
                                                <!-- Menú desplegable -->
                                                <div class="menu-dropdown">
                                                    <a class="btn danger"><ion-icon name="alert-circle-outline"></ion-icon></ion-icon>Reportar</a>
                                                </div>
                                            </div>
                                        {% endif %}
                                        <p class="mb-0">{{ comment }}</p>
                                    </div>
                                {% empty %}
                                    <p class="text-muted">No comments yet. Be the first to comment!</p>
                                {% endfor %}
                            </div>
                            <a class="boton-comentario" href="{% url 'article_detail' article.pk %}">
                                <ion-icon name="pencil-outline"></ion-icon>
                                <span>comentar</span>
                            </a>   
                        </div>
                    </div><!-- /.post-content -->
                </div><!-- /.post-container -->
            {% endfor %}
        </div>
        {% else %}
            <p style="color: var(--color-texto);">No se encontraron artículos.</p>
        {% endif %}
    </div>  

{% endblock %}

app_newspaper/templates/update_profile_picture.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="actualizar-container mt-4">
        <h2 class="text-center">A c t u a l i z a r</h2>
        <div class="profile-form-container">
            <img src="{{ profile.profile_picture.url }}" alt="Foto de perfil" class="mb-3">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Oculta el input file -->
                <input type="file" id="id_profile_picture" name="profile_picture" style="display: none;">
                <!-- Etiqueta que actúa como botón personalizado -->
                <label for="id_profile_picture" class="boton-cargar-imagen">
                    <ion-icon name="cloud-upload-outline"></ion-icon>
                </label>
                <button type="submit" class="boton-guardar-img">
                    <div class="letra-boton-verdadero">
                     Guardar cambios
                    </div>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}




{% comment %} {% block content %}
<div class="profile-form-container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
    </form>
</div>
{% endblock %} {% endcomment %}